"""Allow null years for unanchored families

Revision ID: 1eb3c3596521
Revises: 9cde4b018ef3
Create Date: 2026-09-14 18:21:56.848331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb3c3596521'
down_revision: Union[str, Sequence[str], None] = '9cde4b018ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_families', schema=None) as batch_op:
        batch_op.alter_column('first_seen_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('latest_seen_year',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_families', schema=None) as batch_op:
        batch_op.alter_column('latest_seen_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('first_seen_year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
