"""Add vision extraction fields

Revision ID: 36d803feab41
Revises: 1eb3c3596521
Create Date: 2026-09-15 19:41:14.432622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d803feab41'
down_revision: Union[str, Sequence[str], None] = '1eb3c3596521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_type', sa.String(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_content', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('extraction_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('extraction_confidence', sa.Float(), nullable=True))

    with op.batch_alter_table('study_evidences', schema=None) as batch_op:
        batch_op.alter_column('concept_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_evidences', schema=None) as batch_op:
        batch_op.alter_column('concept_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('assessment_type')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('extraction_confidence')
        batch_op.drop_column('extraction_method')
        batch_op.drop_column('needs_review')
        batch_op.drop_column('structured_content')

    # ### end Alembic commands ###
