"""Question families v1

Revision ID: 9cde4b018ef3
Revises: d308a1817f18
Create Date: 2026-09-14 18:11:58.026431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cde4b018ef3'
down_revision: Union[str, Sequence[str], None] = 'd308a1817f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_seen_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('latest_seen_year', sa.Integer(), nullable=True))
        
        batch_op.alter_column('repetition_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_question_families_subject'), ['subject'], unique=False)
        batch_op.drop_column('name')
        
    op.create_table('question_family_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('decision_method', sa.String(), nullable=False),
    sa.Column('algorithm_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['question_families.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_family_memberships_family_id'), 'question_family_memberships', ['family_id'], unique=False)
    op.create_index(op.f('ix_question_family_memberships_id'), 'question_family_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_question_family_memberships_question_id'), 'question_family_memberships', ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_question_families_subject'))
        batch_op.alter_column('repetition_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
