"""Baseline migration

Revision ID: d308a1817f18
Revises: 
Create Date: 2026-09-14 17:08:09.571838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd308a1817f18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('exam_type', sa.String(), nullable=True),
    sa.Column('document_hash', sa.String(), nullable=False),
    sa.Column('extraction_status', sa.String(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_hash'), 'documents', ['document_hash'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('question_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repetition_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_families_id'), 'question_families', ['id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_course_id'), 'exams', ['course_id'], unique=False)
    op.create_index(op.f('ix_exams_document_id'), 'exams', ['document_id'], unique=True)
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_table('syllabuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabuses_course_id'), 'syllabuses', ['course_id'], unique=False)
    op.create_index(op.f('ix_syllabuses_id'), 'syllabuses', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_exam_id'), 'sections', ['exam_id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_syllabus_id'), 'units', ['syllabus_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.String(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('is_alternative', sa.Boolean(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('cognitive_level', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['question_families.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_family_id'), 'questions', ['family_id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_section_id'), 'questions', ['section_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_unit_id'), 'topics', ['unit_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_id'), 'evidences', ['id'], unique=False)
    op.create_index(op.f('ix_evidences_question_id'), 'evidences', ['question_id'], unique=False)
    op.create_table('question_topic',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'topic_id')
    )
    op.create_table('subtopics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtopics_id'), 'subtopics', ['id'], unique=False)
    op.create_index(op.f('ix_subtopics_topic_id'), 'subtopics', ['topic_id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CANONICAL', 'PROVISIONAL', 'UNRESOLVED', name='conceptstatus'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('subtopic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_canonical_name'), 'concepts', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_concepts_id'), 'concepts', ['id'], unique=False)
    op.create_index(op.f('ix_concepts_parent_id'), 'concepts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_concepts_subtopic_id'), 'concepts', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_concepts_unit_id'), 'concepts', ['unit_id'], unique=False)
    op.create_table('concept_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNRESOLVED', name='mappingconfidence'), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_aliases_alias'), 'concept_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_concept_aliases_concept_id'), 'concept_aliases', ['concept_id'], unique=False)
    op.create_index(op.f('ix_concept_aliases_id'), 'concept_aliases', ['id'], unique=False)
    op.create_table('concept_relationship',
    sa.Column('concept_a_id', sa.Integer(), nullable=False),
    sa.Column('concept_b_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['concept_a_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['concept_b_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('concept_a_id', 'concept_b_id')
    )
    op.create_table('question_concept',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNRESOLVED', name='mappingconfidence'), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'concept_id')
    )
    op.create_index(op.f('ix_question_concept_concept_id'), 'question_concept', ['concept_id'], unique=False)
    op.create_index(op.f('ix_question_concept_question_id'), 'question_concept', ['question_id'], unique=False)
    op.create_table('study_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNRESOLVED', name='mappingconfidence'), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_evidences_concept_id'), 'study_evidences', ['concept_id'], unique=False)
    op.create_index(op.f('ix_study_evidences_document_id'), 'study_evidences', ['document_id'], unique=False)
    op.create_index(op.f('ix_study_evidences_id'), 'study_evidences', ['id'], unique=False)
    op.create_table('syllabus_concept',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('unit_id', 'concept_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syllabus_concept')
    op.drop_index(op.f('ix_study_evidences_id'), table_name='study_evidences')
    op.drop_index(op.f('ix_study_evidences_document_id'), table_name='study_evidences')
    op.drop_index(op.f('ix_study_evidences_concept_id'), table_name='study_evidences')
    op.drop_table('study_evidences')
    op.drop_index(op.f('ix_question_concept_question_id'), table_name='question_concept')
    op.drop_index(op.f('ix_question_concept_concept_id'), table_name='question_concept')
    op.drop_table('question_concept')
    op.drop_table('concept_relationship')
    op.drop_index(op.f('ix_concept_aliases_id'), table_name='concept_aliases')
    op.drop_index(op.f('ix_concept_aliases_concept_id'), table_name='concept_aliases')
    op.drop_index(op.f('ix_concept_aliases_alias'), table_name='concept_aliases')
    op.drop_table('concept_aliases')
    op.drop_index(op.f('ix_concepts_unit_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_subtopic_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_parent_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_canonical_name'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_subtopics_topic_id'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_id'), table_name='subtopics')
    op.drop_table('subtopics')
    op.drop_table('question_topic')
    op.drop_index(op.f('ix_evidences_question_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_topics_unit_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_questions_section_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_family_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_units_syllabus_id'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_exam_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_syllabuses_id'), table_name='syllabuses')
    op.drop_index(op.f('ix_syllabuses_course_id'), table_name='syllabuses')
    op.drop_table('syllabuses')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_document_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_course_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_question_families_id'), table_name='question_families')
    op.drop_table('question_families')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
